### ISSUE TITLE
Smidge error

### ISSUE THREAD

**Issue by cryothic** [usome/UmbracoTagManager#10]
**The problem:**
When I open the tag-manager on a live site, and I click on the default-category, the complete interface is messed up.
`https://imgur.com/CmrhETa`

There are angular properties everywhere, and I can't click on anything.
The browser console has errors like:
`Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.3/$controller/ctrlreg?p0=TagManager.TagDisplayController`
in
`umbraco-backoffice-js.js.v873119da4c6cf89dcb41660f4fadbc3ce6b6a763`

**What I did**
I installed the package locally in Umbraco 13.0.3. That all worked fine.
It doesn't work on the live site.

**Fix**
I've googled on this problem, and it seems a Smidge problem.
Deleting the Smidge folder doesn't help in my case.
Then I found this:
https://our.umbraco.com/forum/using-umbraco-and-getting-started/108316-frontend-error-the-file-umbraco-backoffice-extensions-js-does-not-contain-any-reference-to-the-extension#comment-342724

Adding `"bundleOptions": "None"` to the manifest does solve the problem.

But in my development-site, the package.manifest is overwriten on every build. I guess the TagManager.dll creates it on Build?
Is it possible to add the `"bundleOptions": "None"` to the default package manifest?
It seems to solve some problems (as other packages have this same problem).

**Comment by BishalTimalsina12** [comment]
Subject: Resolution to Tag Manager Interface Issue

Hi @cryothic ,

We identified and resolved the issue. The problem was caused by the ?v= query parameter in the script references, such as "~/App_Plugins/TagManager/backoffice/TagManagerTree/TagManager.controller.js?v=1". 

![TagManager](https://github.com/usome/UmbracoTagManager/assets/143370089/e537422b-2374-45c0-88dc-123a318e7e40)

Removed this parameter, and the interface should now function correctly.

Please make sure to use the latest version of the TagManager.1.0.2, as these fixes have been implemented there. 
If you have any further questions or encounter additional issues, feel free to reach out.


Best regards,

**Comment by cryothic** [comment]
Hi @BishalTimalsina12 
Thanks for the quick response. This solves the problem indeed. 
Great work!
